---
name: Net-Delicious-Export-Post-XBEL
version: 1.4
author:
  - Aaron Straup Cope <ascope@cpan.org>
abstract: |-
  export your del.icio.us posts as 
  XBEL SAX events
license: perl
requires:
  Net::Delicious: >= 0.93
  Net::Delicious::Export: >= 1.2
  String::Random: 0
build_requires:
  Test::Simple: >= 0.47
provides:
  Net::Delicious::Export::Post::XBEL:
    file: lib/Net/Delicious/Export/Post/XBEL.pm
    version: 1.4
generated_by: Module::Build version 0.2611
